target_include_directories( ${PROJECT_NAME} PUBLIC ${SHAKE_INCLUDE_DIRECTORIES} )

target_link_libraries( ${PROJECT_NAME} PUBLIC ${SHAKE_EXTERNAL_LIBRARIES}  )


target_include_directories( ${SHAKE_EXECUTABLE_NAME} PUBLIC ${SHAKE_INCLUDE_DIRECTORIES} )
target_link_libraries( ${SHAKE_EXECUTABLE_NAME} PUBLIC ${SHAKE_EXTERNAL_LIBRARIES}  )